# Generated by Django 5.1.7 on 2025-03-31 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeethStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tooth_number', models.IntegerField()),
                ('status', models.CharField(choices=[('normal', 'Normal'), ('filling', 'Filling'), ('extraction', 'Extraction'), ('missing', 'Missing')], default='normal', max_length=20)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teeth_status', to='Patient.patient')),
            ],
        ),
    ]
