# Generated by Django 5.1.7 on 2025-04-02 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0002_teethstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teethstatus',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_teeth_status', to='Patient.patient'),
        ),
    ]
