# Generated by Django 5.1.7 on 2025-04-12 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0003_alter_teethstatus_patient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='allergies',
        ),
    ]
