# Generated by Django 5.1.7 on 2025-03-31 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Appointment', '0004_appointment_doctor_appointment_notes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='doctor',
        ),
    ]
