# Generated by Django 5.1.7 on 2025-04-03 03:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appointment', '0005_remove_appointment_doctor'),
        ('Patient', '0003_alter_teethstatus_patient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='treatment_type',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Patient.patient'),
        ),
    ]
