# Generated by Django 5.1.7 on 2025-04-02 17:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0003_alter_teethstatus_patient'),
        ('Prescription', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='prescribedmedicine',
            name='is_taken',
            field=models.BooleanField(default=False, help_text='Whether the patient has taken/completed this medicine'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='Patient.patient'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='pending_work',
            field=models.TextField(blank=True, help_text='Description of pending dental work'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='prescription_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='prescription',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='ACTIVE', max_length=20),
        ),
        migrations.AddField(
            model_name='prescription',
            name='work_done',
            field=models.TextField(blank=True, help_text='Description of dental work performed'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='dosage_instructions',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='ToothStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tooth_number', models.IntegerField(help_text='Number of the tooth (1-32)')),
                ('status', models.CharField(choices=[('normal', 'Normal'), ('filling', 'Filling'), ('extraction', 'Extraction'), ('missing', 'Missing'), ('decay', 'Decay'), ('crown', 'Crown'), ('implant', 'Implant')], default='normal', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('treatment_date', models.DateField(default=django.utils.timezone.now)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescription_teeth_status', to='Patient.patient')),
            ],
            options={
                'ordering': ['patient', 'tooth_number'],
                'unique_together': {('patient', 'tooth_number')},
            },
        ),
        migrations.AddField(
            model_name='prescription',
            name='treated_tooth',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescriptions', to='Prescription.toothstatus'),
        ),
    ]
